"""Constants for the wundasmart integration."""

DOMAIN = "wundasmart"

CONF_CONNECT_TIMEOUT = "connect_timeout"
CONF_READ_TIMEOUT = "read_timeout"

DEFAULT_SCAN_INTERVAL = 300
DEFAULT_CONNECT_TIMEOUT = 5
DEFAULT_READ_TIMEOUT = 5

MIN_SENSOR_ID = 1
MAX_SENSOR_ID = 30
MIN_TRV_ID = 31
MAX_TRV_ID = 90
MIN_UFH_ID = 91
MAX_UFH_ID = 94
MIN_ROOM_ID = 121
MAX_ROOM_ID = 150
